### ISSUE TITLE
Please add support for disabling when entering fullscreen application

### ISSUE THREAD

**Issue by SivertGullbergHansen** [r-Larch/MouseTrap#12]
Would be a nice feature if the tool automatically disabled itself when entering e.g. a game that contains/locks the cursor 😄

**Comment by r-Larch** [comment]
Hi,

sorry for responding that late.

Since version 1.0.6 there is a option to disable mouse teleportation in the right click menu of the tray icon.
Automatically detecting a borderless game that locks the cursor would require an accessible Win32 API, but I don't know any such API. There is only an API to lock the cursor, but this API can not be used to read the cursor lock state. 
So there is no way to detect such a case.

So at the time now I don't implement a auto-detection mechanism.

![Tray icon](https://raw.githubusercontent.com/r-Larch/MouseTrap/master/images/tray-snap.jpg)

kind regards
René
