### ISSUE TITLE
Unexpected Cursor Teleportation

### ISSUE THREAD

**Issue by wildmanlennox** [r-Larch/MouseTrap#2]
on some passes between monitors, the cursor will jump to the center of the next screen

**Comment by r-Larch** [comment]
This is most likely because of my simple fix to a weird windows behavior.
Where windows does not allow the mouse to travel across desktop regions that are not painted to any screen.

### Example:
```
  ___________  ____________
 |           | not painted |
 |           |_________
 |  Sceen1   |         |
 |           | Sceen2  |
 |___________|_________|
```

### Problem:
	The mouse can not move between two points when the straight line connecting both points goes through a not painted region.

### Simple Solution:
	For every teleportation, move the mouse to the center of the target screen and from there move it to the destination position.

### Advenced Solution:
	Do some fancy math to always find the rigth path.

### Could this be the case for you?
Can you please send me a screenshot of the "Mousetrap Settings" window where your screens setup is visible?

**Comment by wildmanlennox** [comment]
Further Info: the problem can be reproduced at any location between monitors, simply wiggle the mouse back and forth and it will happen eventually.
![image](https://user-images.githubusercontent.com/47006620/57547985-df626180-732d-11e9-84f2-e1d4f070f1a8.png)

**Comment by r-Larch** [comment]
Thanks, I will see what i can do.

**Comment by Majzer** [comment]
It's still happening.

**Comment by ThaBoss07** [comment]
Just downloaded and testing. This issue still exists. Mouse will jump to center of screen you are moving cursor to. Will update if more problems arise but so far super smooth.

**Comment by r-Larch** [comment]
@ThaBoss07 I can't reproduce this bug on any computer or configuration.

Can you specify your configuration?
- The exact resolution and offset of each screen. (The "Mousetrap Settings" screen should contain this information)
- Your configuration under `%APPDATA%\MouseTrap\ScreenConfigCollection.json`
- Your Windows 10 build number?
- At which scaling run your screens? (`WIN+i` -> System -> Display -> Scale and layout)
- The exact conditions at which the mouse gets teleported wrong:
  - Position on screen.
  - Movement direction and speed.
  - Did you drag something, for drag and drop?
  - Do you have high CPU usage while the problem arises?
  - Do you have programs running with administrator permissions (visible in the foreground)?
  - Where there any fullscreen applications running, like games or movies?
  - Do you have any specialized device drivers?
  - Can you think of anything else worth mentioning here?

**Comment by lxk3il** [comment]
I just did a fresh install and can confirm this issue with the following setup:
```json
[{"ScreenId":0,"Name":"Screen1","TopBridge":null,"LeftBridge":null,"RightBridge":{"TopOffset":0,"BottomOffset":361,"TargetScreenId":1},"BottomBridge":null},{"ScreenId":1,"Name":"Screen2","TopBridge":null,"LeftBridge":{"TopOffset":0,"BottomOffset":0,"TargetScreenId":0},"RightBridge":null,"BottomBridge":null}]
```

- Windows build is 19041.630
- Scaling is 150%

@wildmanlennox already described how the problem can be reproduced, for example by wiggling the mouse back and forth between screens

**Comment by r-Larch** [comment]
# Mousetrap v1.0.6 is released

In this version, I've done some optimizations regarding this Problem.
Please try it out and report back if the issue is resolved.

## Changelog

### Version 1.0.6

 - **Migrate to .NET 5** _(from legacy .NET Framework)_
 - Adds **Diagnostic Window**
   - Realtime Log Viewer
   - Configutation Viewer
   - LogFile Viewer
 - Implements a **potential fix** for **[#2 Unexpected Cursor Teleportation](https://github.com/r-Larch/MouseTrap/issues/2)**
 - Adds an option to **disable Mouse teleportation** - That's usefull while gaming in fullscreen!
 - Lots of smaller bugfixes

**Comment by lxk3il** [comment]
Thanks for the update! 
I just tested it, but unfortunately it seems that the issue still persists. 

Setup is the same as described in https://github.com/r-Larch/MouseTrap/issues/2#issuecomment-731729920

**Comment by r-Larch** [comment]
Can you please reproduce the bug with realtime loggong on, in the new diagnostic window, and send me then the diagnostic data to analyze.

Thanks for this quick reaction

**Comment by lxk3il** [comment]
I did a complete reinstall of the new release now and the problem seems to be solved now. No more cursor teleportation.
Will observe it further and let you know, when the problem arises again.

But it seems to be fixed for now, thank you very much!

**Comment by r-Larch** [comment]
I'm happy to hear that, 
thank you.

I suspect on your first try you got the victim of my mechanism to only keep one instance running, because this mechanism awakes the running instance (if there is one) instead of running a new one. This means you can double click on the new version and what happens is, it opens the settings screen of the old (currently running) version.

Have a nice day!
