### ISSUE TITLE
Fullscreen Games

### ISSUE THREAD

**Issue by tkielarbb** [r-Larch/MouseTrap#7]
Hello
There is a problem that occures in certain games. Lately i discovered it in Layers of Fear 2 , and Pacify. When you turn to one side mouse can go to the second monitor and click out of the game. After closing MouseTrap the problem is gone. I believe it's bad implementation of Fullscreen mode of the game but is there any way to fix it?

**Comment by r-Larch** [comment]
# Mousetrap v1.0.6 is released

In this version, I've added an option to disable mouse teleportation.
You may find it useful because of the way mouse teleportation gets 
done by mousetrap will always interfere with fullscreen games.
(It uses the same mechanism to trap the mouse inside a rectangle)

## Changelog

### Version 1.0.6

 - **Migrate to .NET 5** _(from legacy .NET Framework)_
 - Adds **Diagnostic Window**
   - Realtime Log Viewer
   - Configuration Viewer
   - LogFile Viewer
 - Implements a **potential fix** for **[#2 Unexpected Cursor Teleportation](https://github.com/r-Larch/MouseTrap/issues/2)**
 - Adds an option to **disable Mouse teleportation** - That's useful while gaming in fullscreen!
 - Lots of smaller bugfixes
