### ISSUE TITLE
Pause/Resume QOL Fixes

### ISSUE THREAD

**Issue by Th3N3rdyGam3r** [r-Larch/MouseTrap#8]
There are two things that I think can be improved with the temporary disabling of mouse teleportation.
1. Adding an option to pause/resume in the right-click menu of the tray icon. This would make it easier to pause before opening a fullscreen game
2. Auto-detection for pause/resume. My thinking was something similar to BorderlessGaming where you can add a proccess/exe that, when started, would automatically pause the mouse teleportation until it is closed. For example, I know Genshin Impact doesn't work with mouse teleportation, so I would add the game's process or exe to a list so that mouse teleportation is disabled as long as the game is still running.

**Comment by r-Larch** [comment]
Hi,

sorry for responding that late.

Since version 1.0.6 there is a option to disable mouse teleportation in the right click menu of the tray icon.
Automatically detecting a borderless game would require an accessible Win32 API, but I don't know any such API.
So at the time now I don't implement a auto-detection mechanism.

![Tray icon](https://raw.githubusercontent.com/r-Larch/MouseTrap/master/images/tray-snap.jpg)

kind regards
René
